### ISSUE TITLE
Remember last-used session

### ISSUE THREAD

**Issue by glitchcrab** [artur9010/lightdm-webkit-material#10]
I have several DEs installed but I primarily use I3, however it is not at the top of the list. Other greeters have the ability to remember the last-used session and set that each time - is it possible for this to be implemented?

**Comment by artur9010** [comment]
Thanks for the suggestion. I'm afraid that I have difficulty in writing this (lack of documentation)

**Comment by glitchcrab** [comment]
I cheated slightly with this and removed the session .desktop files in /usr/share/xsessions/ for the other DEs - this obviously works in the shortterm but if it were possible to do this through the greeter that would be great.

I tried changing 'user-session' in lightdm.conf but that had no effect. Additionally, my /home/user/.dmrc file lists i3 as the last-used session so that is also correct.
