### ISSUE TITLE
How can I change the default font of the theme ??

### ISSUE THREAD

**Issue by iosmanthus** [artur9010/lightdm-webkit-material#20]
Due to i know little about css and html ,i don't know how to change the font hinting and the font type.
Could you tell some details to me ?? Please. Thank you!

**Comment by FallingSnow** [comment]
Read this http://nicewebtype.com/notes/2009/10/30/how-to-use-css-font-face/.

The just of it is, add the font file to the fonts directory, create an `@font-face` rule in the style.css file. Then add the `font-family` rule here https://github.com/artur9010/lightdm-webkit-material/blob/master/assets/css/style.css#L8-L12. That will apply it to the whole login screen.

**Comment by iosmanthus** [comment]
Thanks!
