### ISSUE TITLE
Please help me with your webkit theme

### ISSUE THREAD

**Issue by tjw0lf** [artur9010/lightdm-webkit-material#21]
How can i make your login block transparent or smaller

**Comment by FallingSnow** [comment]
Login block?

**Comment by tjw0lf** [comment]
The box that you type the username and password

**Comment by FallingSnow** [comment]
Edit the `style.css` file and add `background: transparent;` to the md-card section.

**Comment by tjw0lf** [comment]
I'm not talking about the wallpaper i put one in. talking about the box that you type in username and password. I have looked in the style.css is not in there. You should take  a look then tell me where to go please

**Comment by FallingSnow** [comment]
I'm completely correct. https://github.com/artur9010/lightdm-webkit-material/blob/master/assets/css/style.css#L23

**Comment by tjw0lf** [comment]
OK i see now thank you i will try that. thanks very much. Also would it be possible to resize its or take it out and have just the username and password bars. just so its easier to see the wallpaper

**Comment by FallingSnow** [comment]
Yes, just more CSS modification. Set things like the avatar and welcome back bar to `display:none`. I suggest you learn a little CSS, it's really easy and useful. This document contains info on using classes and IDs like in the style.css file. http://mobile.htmlgoodies.com/beyond/css/article.php/3865211

**Comment by tjw0lf** [comment]
Thank you that helps alot. :+1:  :)

**Comment by tjw0lf** [comment]
One more thing how would i changed the blue font text in the md card and the blue and gray color on the scroll bar. i cannot find those colors anywhere in the css file

Thank you
