### ISSUE TITLE
The Login UI is not showing

### ISSUE THREAD

**Issue by ghost** [artur9010/lightdm-webkit-material#22]
Hi, i'm using Antergos (Arch Linux). I tried to install the material theme as per instructions. After reboot nothing shows on the Login interface. I changed back the settings and tried to apply the configurations changes again, but this time I ran the command **lightdm-webkit2-greeter** for a fast preview. The Interface is still blank and on the console, I have the following message:

*\* (WebKitWebProcess:2967): WARNING **: No LIGHTDM_TO_SERVER_FD environment variable

*\* (WebKitWebProcess:2967): WARNING *_: No LIGHTDM_FROM_SERVER_FD environment variable
*_file:///usr/share/lightdm-webkit/themes/material/assets/js/app.js:3:26: CONSOLE DEBUG webkit-material loading...
file:///usr/share/lightdm-webkit/themes/material/assets/bower_components/angular/angular.min.js:40:315: CONSOLE ERROR SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
**
(lightdm-webkit2-greeter:2958): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkWidget'

(lightdm-webkit2-greeter:2958): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2958): Gtk-CRITICAL **: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2958): Gdk-CRITICAL **: gdk_window_lower: assertion 'GDK_IS_WINDOW (window)' failed

(lightdm-webkit2-greeter:2958): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkWidget'

(lightdm-webkit2-greeter:2958): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2958): Gtk-CRITICAL **: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2958): Gdk-CRITICAL **: gdk_window_lower: assertion 'GDK_IS_WINDOW (window)' failed

(lightdm-webkit2-greeter:2958): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkWidget'

(lightdm-webkit2-greeter:2958): Gtk-CRITICAL **: gtk_widget_get_toplevel: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2958): Gtk-CRITICAL **: gtk_widget_get_window: assertion 'GTK_IS_WIDGET (widget)' failed

(lightdm-webkit2-greeter:2958): Gdk-CRITICAL **: gdk_window_lower: assertion 'GDK_IS_WINDOW (window)' failed

I tried Googling for a possible solution and got nothing so far. Can anyone help???

**Comment by MTRNord** [comment]
Same issue here

**Comment by FallingSnow** [comment]
To be honest I'm not really sure what the cause it here. Firstly, can you try getting the logs from an real login `systemctl restart lightdm`. The `No LIGHTDM_TO_SERVER_FD` is scaring me :fearful:. Then post the `/var/log/lightdm/lightdm.log` and `/var/log/lightdm/x-0-greeter.log`. I also don't get the security error you're seeing.

Also make sure your `webkit2gtk` is up to date, my version is 2.12.0-2.

**Comment by FallingSnow** [comment]
Well I just updated my laptop and I got a black screen now.

**Comment by FallingSnow** [comment]
https://github.com/FallingSnow/lightdm-webkit-material contains the fixes for the blackscreen. You can now sign in but saving any kind of settings is broken. I will make a pull request once a solution to saving settings has been found.

**Comment by ghost** [comment]
working like a charm ;). 
Thanks

**Comment by spamtime** [comment]
@FallingSnow , Does not work for me (arch linux). I tried first updating it with git pull, nothing changed. Tried with git clone and do it all over - still black screen and doesn't work as it was before the update on Friday.

Getting this error when running the lightdm-webkit2-greeter command:
`*\* (WebKitWebProcess:14493): WARNING **: No LIGHTDM_TO_SERVER_FD environment variable

*\* (WebKitWebProcess:14493): WARNING **: No LIGHTDM_FROM_SERVER_FD environment variable
file:///usr/share/lightdm-webkit/themes/material/assets/js/app.js:3:26: CONSOLE DEBUG webkit-material loading...
file:///usr/share/lightdm-webkit/themes/material/assets/bower_components/angular/angular.min.js:40:315: CONSOLE ERROR SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
`

**Comment by FallingSnow** [comment]
@spamtime, your still using the wrong repository, mine is completely different. Double check the link above and clone that.

**Comment by spamtime** [comment]
@FallingSnow this is what I pulled at first (to update the current content, and it updated some files successfully) when I saw the topic - https://github.com/FallingSnow/lightdm-webkit-material
After that i deleted everything and cloned the same link, did my lightdm.conf (and greeter) settings and still a black screen.

**Comment by FallingSnow** [comment]
Try cloning it into a separate directory and changing the settings in `lightdm-webkit2-greeter.conf` to that directory.

**Comment by spamtime** [comment]
I got it to work now, had to do some debug. 
The way you suggested didn't work or probably I haven't configured in the right way. What I did was to restore my old files and I saw that assets, .git and nbproject weren't updating from your repository, so I manually deleted them > copied everything from your files to /usr/share/lightdm-webkit/themes/lightdm-webkit-material and also changed the lightdm-webkit2-greeter file to point to **lightdm-webkit-material** instead of **material** (like it was before). 

I still haven't tried it if it saves settings of some sort that you mentioned, but I'm glad you did some work to fix it. Keep it up and I hope that this helps :)

**Comment by FallingSnow** [comment]
Wow this really stinks. Seems like upstream devs are really divided on the fix for this issue. Seems like I will actually need to make a long term solution to saving settings.

**Comment by spamtime** [comment]
Yup, saving the settings doesn't work. Strangely enough, when i run the lightdm-webkit2-greeter command, I have my custom icon on top, but when logging in there is blank space on the place on the icon. Not sure if it is connected.

There was an update from AUR (when using yaourt -Syyau) for the lightdm-webkit-material theme, but not sure what has been changed, since there is still a black screen.

**Comment by FallingSnow** [comment]
Seems like the devs have decieded on a fix, now we just have to wait for it to land. I believe the fix will correct both the old (broken/blackscreen) version and the the current one, settings will work again.

https://bugs.webkit.org/show_bug.cgi?id=156651

**Comment by FallingSnow** [comment]
@guambejr You can close this issue now, webkit2gtk 2.12.2 fixes this issue.

**Comment by ghost** [comment]
:D. Thnks!
