### ISSUE TITLE
(Archlinux) Black screen on login if lang not set

### ISSUE THREAD

**Issue by ajoubert** [artur9010/lightdm-webkit-material#24]
Hi !

I don't have the time to fork and make a pull request for this right now, but I noticed a bug that you might want to fix : if the default language variable is not set in /etc/environment on archlinux, some javascript crashes somewhere in assets/bower_components/ resulting in a black screen.

If it is not done by then, I might have some time to look into it this week end, or at least reproduce the bug to send you the logs.

Easy fix though, and great theme, thank you for your work !

**Comment by LeereMenge** [comment]
having the same issue, what exactly did you write into /etc/environment?

**Comment by Gingernaut** [comment]
I've been experiencing this issue I believe, was wondering if it was a problem with lightdm. I see I'm missing my language in /etc/environment; what should go there to fix the issue? (LANG=en_US.UTF-8)?

**Comment by ajoubert** [comment]
In my case, LANG=en_US.utf8 fixed it indeed, I didn't check if it worked for all languages though.

**Comment by ajoubert** [comment]
(Sorry failed closing issue, github newbie ><, didn't expect "close and comment" to actually close the issue but simply my comment box...).

Anyhow, yes adding "LANG=en_US.UTF-8" in my /etc/environment fixed it for me, so if you experience the same problem give it a try, it is definitively linked to this theme.

**Comment by Zjemm** [comment]
I did a frech arch install with xfce and lightdm, but when i'm using this theme i get the black screen and cannot login. even though i set "LANG=en_US.UTF-8" in /etc/environment

i also tested ghtdm-webkit-google, the is see the the theme as expected, but clicking login, does not do anything.
reverting back to default works without any problems.

any idea? i really love the look of this theme

**Comment by Gingernaut** [comment]
Adding LANG=en_US.UTF-8 didn't fix it for me either.

**Comment by FallingSnow** [comment]
Can anyone having this issue add this above [line 260](https://github.com/artur9010/lightdm-webkit-material/blob/master/assets/js/app.js#L260) in the `app.js` file so it looks like this:

``` javascript
259 // Load possible languages
260 console.debug(lightdm.languages);
261 factory.languages = lightdm.languages;
```

The file should be located at `/usr/share/lightdm-webkit/themes/material/assets/js/app.js`.
Then please provide the output of the log located at `/var/log/lightdm/x-0-greeter.log`.

**Comment by mpbelhorn** [comment]
Not sure if my problem is the same. I do have LANG=en_US.UTF-8 in /etc/environment:

```
$ localectl 
   System Locale: LANG=en_US.UTF-8
                  LC_TIME=en_DK.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
     X11 Variant: caps:ctrl_modifier
```

but here is the log after adding `console.debug(lightdm.languages);`

```
$ lightdm --test-mode --debug
^C
$ cat HOME/.cache/lightdm/log/x-1-greeter.log 

** (process:18739): WARNING **: Failed to open CK session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
file:///usr/share/lightdm-webkit/themes/material/assets/js/app.js:3:26: CONSOLE DEBUG webkit-material loading...
file:///usr/share/lightdm-webkit/themes/material/assets/js/app.js:260:26: CONSOLE DEBUG [object LightDMLanguage],[object LightDMLanguage]
file:///usr/share/lightdm-webkit/themes/material/assets/js/app.js:108:30: CONSOLE DEBUG Updating background... trianglify
file:///usr/share/lightdm-webkit/themes/material/assets/js/mock.js:192:16: CONSOLE LOG Password: 

(lightdm-webkit2-greeter:18742): Gdk-WARNING **: lightdm-webkit2-greeter: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.


(WebKitWebProcess:18753): Gdk-WARNING **: WebKitWebProcess: Fatal IO error 0 (Success) on X server :1.
```

**Comment by FallingSnow** [comment]
@mpbelhorn Thank you. Unfortunately I don't believe your problem is related. Are you also receiving a black screen?

**Comment by mpbelhorn** [comment]
Check: one big black screen using this and other non-simple lightdm-webkit2-greeter themes. I was trying to use this theme on an arch VM on my work machine. 

However, I suspect my problem is not related. I run this theme on my personal laptop without issues but will double check tonight that nothing broke recently. I will move my input to the right issue thread once I narrow it down.
