### ISSUE TITLE
AUR Update Notifications?

### ISSUE THREAD

**Issue by ghost** [artur9010/lightdm-webkit-material#25]
I am getting lightdm-webkit-material-git as updatable after updating it.

**Comment by Zerqz** [comment]
I'm getting the same thing, updated 5 times in a row and still get it every time. 

Using packer not yaourt.

**Comment by frenchbeard** [comment]
Using yaourt, packer and pretty much any aur helper / wrapper does not change the fact that the version is not updated properly on latest version => takes the git version over the PKGBUILD version, which should not happen.
