### ISSUE TITLE
Setting profile picture

### ISSUE THREAD

**Issue by camsn0w** [artur9010/lightdm-webkit-material#27]
Add Icon=/var/lib/AccountsService/icons/youraccountname
^ This is incorrect ^
Should be:
Add Icon=/var/lib/AccountsService/icons/youraccountname/stupidicon.png

**Comment by FallingSnow** [comment]
Why?

**Comment by camsn0w** [comment]
Because it doesn't work.

**Comment by FallingSnow** [comment]
Are you sure you didn't place the icon in the wrong directory and that's why it didn't load?

**Comment by FallingSnow** [comment]
The [arch wiki](https://wiki.archlinux.org/index.php/LightDM#Changing_your_avatar) specifies it the current way.

**Comment by camsn0w** [comment]
I'm Sure try it yourself

**Comment by FallingSnow** [comment]
I have, that is how this [screenshot ](https://camo2.githubusercontent.com/7dff3ed6f7e7293e80cfa17906e76ce972066a89/68747470733a2f2f63646e2e7261776769742e636f6d2f6172747572393031302f6c69676874646d2d7765626b69742d6d6174657269616c2f73637265656e73686f6f74732f637573746f6d2d6261636b67726f756e642d616e642d70726f66696c652d696d6167652e706e67) came about. That's strange that this happens for you, if more people report similarly then I will look into it further.

**Comment by camsn0w** [comment]
Alright, I'm using antergos on the Lts kernel, I'll try to see if I can
reproduce it in a vm
