### ISSUE TITLE
Black screen if accountsservice is not present [Arch]

### ISSUE THREAD

**Issue by justas-d** [artur9010/lightdm-webkit-material#28]
The greeter shows nothing but a black screen if the package accountsservice is not on the system.

Issue - The AUR PKGBUILD does not list accountsservice as a dependency.

**Comment by FallingSnow** [comment]
That's strange. I imagine this is a lightdm-webkit2-greeter issue. You may open an issue with them [here](https://github.com/Antergos/lightdm-webkit2-greeter/issues).

**Comment by jaredrholley** [comment]
Installing the accountsservice package fixed my black screen issue.

**Comment by oliveagle** [comment]
same here.
