### ISSUE TITLE
Login menu looks really big

### ISSUE THREAD

**Issue by soppelmann** [artur9010/lightdm-webkit-material#29]
I'm using a 2560x1080 screen and all the menus look really big but I couldn't find anything about resizing them.
Any tips?

**Comment by FallingSnow** [comment]
This is why your having that issue: https://github.com/artur9010/lightdm-webkit-material/blob/master/assets/css/style.css#L84-L126

I targeted 4K screens when I wrote that. I think I'll add a gui scale option in the settings, but idk when that will actually come to fruition. Changing `min-width:2000px` to `min-width:3000px` on line 84 is a quick hack solution.
