### ISSUE TITLE
Greeter recently became unbearably slow

### ISSUE THREAD

**Issue by MarcelRobitaille** [artur9010/lightdm-webkit-material#30]
Recently, whenever I lock my screen, the password field has become very slow; the characters appear in the box seconds after I type them. The dropdowns also take a few seconds to respond. My mouse moves as expected.

When trying to debug the issue, I switched to tty2 and ran the `top` command which showed that my cpu load was less than 10% on all cores and my memory was only about 50% used.

I know it's a problem with the theme because other webkit themes (antergos) are perfectly responsive.

`lightdm -v`:

```
lightdm 1.18.2
```

The theme is the latest version from the master branch.

`uname -a`:

```
Linux Hermes4.6.4-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
```

I'd really like to get this working as it is a beautiful theme.

**Comment by FallingSnow** [comment]
This is because webkit2gtk doesn't have the same performance as native. Whether this is due to hardware acceleration or something else I don't know. Try changing the background to be simpler.

Adding a 4k image as my background has a similar effect, the password field dots show up about a second after I type. However I just accept it because I like the 4k background. :smile:

**Comment by MarcelRobitaille** [comment]
@FallingSnow I don't think that was it because a few days ago it was perfectly responsive.

**Comment by FallingSnow** [comment]
Strange. Well the theme didn't update. So it must be something upstream.

**Comment by MarcelRobitaille** [comment]
@FallingSnow I guess it must be. That would be weird because as I said the antergos theme works perfectly.

**Comment by FallingSnow** [comment]
Never mind, I recently updated and know exactly what you mean. It is extremely slow. Will look into it when I get the chance.

**Comment by MarcelRobitaille** [comment]
Perfect. Thanks.

**Comment by isbirkan** [comment]
Hi guys! I am having the same problem. Has anyone figured out what the problem is? Or do you have a starting point to start investigating it?

**Comment by FallingSnow** [comment]
I did some investigating and I think it has something to do with modesetting. It's already known that modesetting causes severe performance issues on lightdm-webkit2.

My theory is there was some kind of update in our systems that made our systems fallback to modesetting. Thus resulting in the bad performance.

I have been able to get my system to run without modesetting but the resolution gets stuck at a very low resolution. However the performance was very good.

Unfortunately it does not look like modesetting support will come anytime soon.

**Comment by isbirkan** [comment]
That's not very good news. I wouldn't want low resolution in the favor of performance. I will most probably leave lightdm-webkit2. Thanks for the information FallingSnow! Much appreciated!

**Comment by MarcelRobitaille** [comment]
How did you go about running without modesetting?

**Comment by FallingSnow** [comment]
I installed `xf86-video-mesa` and `xf86-video-fbdev` and set `nomodeset` as a kernel option.

**Comment by FallingSnow** [comment]
Actually there is hope yet guys: https://bugs.webkit.org/show_bug.cgi?id=160491

This issue may already be fixed but not released.

**Comment by FallingSnow** [comment]
Good news. That patch does fix it. I installed `webkit2gtk-unstable 2.13.4-1` and manually applied the patch from the link above.

However the performance isn't great, it's just back to what it used to be.

**Comment by MarcelRobitaille** [comment]
Performance used to be fine for me. Thanks for the update!
