### ISSUE TITLE
Does not select correct session for different users

### ISSUE THREAD

**Issue by f4hy** [artur9010/lightdm-webkit-material#31]
I have two users (say user1 and user2) who have DIFFERENT values in /var/lib/AccountsService/users/*

User1 has
`XSession=i3`
and User2 has
`XSession=gnome-classic`

However when the gretter shows up, it shows User1 and i3, as one expects, but then selecting User2, it still shows i3, when it should load the session for user2.

**Comment by FallingSnow** [comment]
This theme always defaults to the last used session and it is theme wide, not independent to each user.
