### ISSUE TITLE
UI Glitches During Interactions and Transitions

### ISSUE THREAD

**Issue by ghost** [artur9010/lightdm-webkit-material#7]
Random black artifacts appear (usually on the left half of the screen) when interacting with the UI.  Changing the session, accessing settings, and even typing can cause this. 

![img_20151211_194011](https://cloud.githubusercontent.com/assets/5511722/11760037/3f7c8cfa-a03f-11e5-9a46-336d73e76a20.jpg)
Apologies for the photo quality, I'm not sure how to scrot a login screen. 

One other small thing: the password field is also not selected by default, making an extra click necessary on a single-user computer.

**Comment by artur9010** [comment]
I think it's a lightdm-webkit2-greeter bug.
I have this same bug (artifacts) on other webkit themes.

https://github.com/Antergos/lightdm-webkit2-greeter/issues/14

**Comment by ghost** [comment]
You're probably correct. At first I thought maybe it was a JavaScript or CSS issue, but I've had various problems like this with a vast majority of WebKit greeter themes.

**Comment by AdrienLemaire** [comment]
Same issue here, especially buggy when using the touchscreen
